NOISSUE-1 Fixed behavior
ochosi/best-practice pull request #2
Opened 2023-12-15 13:57 UTC by schuellerf

Several fixes to the behavior, removed SMELL and updated wording

please comment if these an eligible changes

2023-12-15 13:58 UTC, schuellerf commented
... also the "bad" commit messages don't cause an "exit 1" but that might be on purpose?

2023-12-15 23:03 UTC, ochosi commented
> ... also the "bad" commit messages don't cause an "exit 1" but that might be on purpose?

The idea was to not really block on Jira tickets to not make life hard/er for external contributors. They _can_ create Jira issues (because our project is public), but do we really want to force them to?

2023-12-15 23:04 UTC, ochosi requested changes

2023-12-15 23:04 UTC, ochosi commented on .github/workflows/best-practice.yml
> +        run: if [ -z $(grep -Eo "[A-Z][A-Z0-9]+-[0-9]+" <<< "${{ github.event.pull_request.title }}") ]; then echo "Please add a Jira ticket to the PR title."; exit 1;else echo "Well done!"; fi
```suggestion
        run: if [ -z $(grep -Eo "[A-Z][A-Z0-9]+-[0-9]+" <<< "${{ github.event.pull_request.title }}") ]; then echo "Please add a Jira ticket to the PR title."; else echo "Well done!"; fi
```

2023-12-21 08:12 UTC, ochosi approved these changes
LGTM!

2023-12-21 08:13 UTC, merged